### ISSUE TITLE
Unable to access this over lan

### ISSUE THREAD

**Issue by contactwajeeh** [ridhwaans/homehost#1]
Hello Ridhwaans,

Great initiative by the way, I tried to set this up works good locally on the machine where I set this up but unable to access it on my lan using different machine. Is there any additional configuration required to get this working on lan. Please advise.

The issue I am facing is the app loads up fine, shows all the movies in the catalog but when I open any of it, the player becomes inactive (as if all the controls greys out and I cannot do anything with that). Appreciate your time and thanks in advance.

Regards,
Mohammed Wajee

**Comment by ridhwaans** [comment]
hi @contactwajeeh. In `client-v1.1.0` you would have to search and replace `localhost:<port>` with the ip address of your computer in the lan.  
If that doesnt work, I would check if the `fs_path` in your movies json is pointing to the right location on the filesystem. See `https://github.com/ridhwaans/homehost#naming-conventions`

**Comment by contactwajeeh** [comment]
All good now, thanks appreciate your response.
