### ISSUE TITLE
G

### ISSUE THREAD

**Issue by qwertyqop** [ridhwaans/homehost#11]
My title is messed up but I don’t know how to go apon  calling  /api/generate after running yarn start-dev. 
I know this is a very simple issue but please help me fix it.

**Comment by ridhwaans** [comment]
after running `yarn start-dev` on the latest master, go to `http://localhost:5000/api/generate` on the browser

**Comment by qwertyqop** [comment]
Does it have to be localhost or can I connect through lan?

**Comment by ridhwaans** [comment]
replace localhost with your local ip address

**Comment by qwertyqop** [comment]
Whenever I try to connect I get 

192.168.0.2 is currently unreachable.
ERR_CONNECTION_FAILED

I know that that is the correct address and I am trying to connect to port 5000.

**Comment by ridhwaans** [comment]
If you are running on the same machine, `localhost` and by ip works (`http://192.168.0.2:5000/...`)  
Use the ip address url if opening from another computer. Check your network or firewall settings  
  
`localhost` is referenced in 3 files:  

- `client\src\utils\registerServiceWorker.js`: line 12  
- `client\webpack.config.js`: line 23  
- `server.js`: lines 173, 203, 260, 288  

also, see https://github.com/ridhwaans/homehost/issues/1

**Comment by qwertyqop** [comment]
Thank you.
