### ISSUE TITLE
Cannot get tv/

### ISSUE THREAD

**Issue by itsrxns** [ridhwaans/homehost#14]
All works fine for movie but when I try to load movie series like anime it don't find the media..

tv.json file path is: http://192.168.1.107:5000/tv/90215/1/1
error in browser: Cannot GET /tv/90215/1/1

Directory name: Isekai_Cheat_Magician 90215
File name: S1E1 Isekai Cheat Magician
File extension: .mp4

Terminal output:
[0] Generating data for TV...
[0] GET: F:\contenuti\SerieTV\Isekai_Cheat_Magician 90215
[0] url: https://api.themoviedb.org/3/tv/90215?api_key=MY_API_KEY
[0] GET: F:\contenuti\SerieTV\Isekai_Cheat_Magician 90215\S1E1 Isekai Cheat Magician.mp4
[TV] File saved

I don't find errors..

**Comment by ridhwaans** [comment]
TV is not complete. there is still work to do on playing TV content

**Comment by Dhop84** [comment]
Any news on the Android version ?

**Comment by ridhwaans** [comment]
Work has not started on an Android app. It has no release date.

**Comment by ridhwaans** [comment]
can you try TV again. note - mp4 format is best for the player. not every mkv codec plays well. real time transcoding is slow and doesnt meet the streaming standards
