### ISSUE TITLE
cannot find module './movies.json'

### ISSUE THREAD

**Issue by anonygituser** [ridhwaans/homehost#15]
It shows this error message on starting the server. How to fix this

**Comment by ridhwaans** [comment]
1. create a file as `./server/data/movies.json`  
```
{
"movies": []
}
```  
2. follow instructions on setup and generating data from `README`

**Comment by ridhwaans** [comment]
This is not needed anymore. [Release v1.9](https://github.com/ridhwaans/homehost/releases/tag/v1.9) moves to a self-managing server DB.
