### ISSUE TITLE
HEVC encoded movies playing with audio only

### ISSUE THREAD

**Issue by contactwajeeh** [ridhwaans/homehost#2]
only audio stream plays if we play an  HEVC encoded movie, if the movie is encoded with AVC then it plays fine.

**Comment by farfeduc** [comment]
@contactwajeeh : To my knowledge there is no transcoding in this project. This is a browser-related limitation. Look at the "Can I Use" website for current compatibility : https://caniuse.com/#feat=hevc

**Comment by contactwajeeh** [comment]
Yes, very true. I learned it after sometime I opened this issue, forgot to update it here and close the issue as its not related to the app anymore. Thanks for the headsup.
