### ISSUE TITLE
Movie metadata could not be generated

### ISSUE THREAD

**Issue by aspirat2110** [ridhwaans/homehost#3]
Hello,
I just installed this on a fresh installation of Ubuntu 17.10.
The Music is imported just fine, but I can't get the movies to work. (maybe I just don't understand how to name them right).
I named them like "603-the-matrix.mp4" or "604-the-matrix-reloaded.mp4".
Do I have to name them something different?

**Comment by ridhwaans** [comment]
hi @aspirat2110. The app identifies the movie ID at the end of the filename. I think you need to put the ID at the end of the filename like `the-matrix-reloaded-604.mp4` or `the-matrix-reloaded.604.mp4` or `the-matrix-reloaded 604.mp4`  
see https://github.com/ridhwaans/homehost#naming-conventions for more details  
Cheers

**Comment by aspirat2110** [comment]
Thank you!
`the-matrix-reloaded-604.mp4` worked!
