### ISSUE TITLE
Feature - Read from nfo and tags

### ISSUE THREAD

**Issue by h4wkmoon** [ridhwaans/homehost#5]
Hi, 
is it possible to make your app able to read infos from .nfo file (for movies and tv shows), and from id3 tags (for music) ?

**Comment by ridhwaans** [comment]
its possible but why? its xml and the apis fetch that and more. its a nice todo for migration support from other services

**Comment by h4wkmoon** [comment]
Well, why asking an external API when you already have the information at hand ?

**Comment by ridhwaans** [comment]
Thats how I initially built it. I dont have nfos and tags

**Comment by h4wkmoon** [comment]
For nfos, i get it. If you don't have sonarr, sickrage, lidarr, radarr, it get that you don't use nfos.
For MP3 tags, well, that's another story. They are embedded into the files.

Never mind. After all, it's your app. I can't code in node and do it myself, anyway.
I think you should close this issue.
