### ISSUE TITLE
Support more audio formats

### ISSUE THREAD

**Issue by trwnh** [ridhwaans/homehost#8]
From the readme it looks like only .mp3 streaming is supported. My collection is in FLAC, and I would like to stream in Opus ideally. It would be nice to be able to use something that is not MP3...

**Comment by Dhop84** [comment]
It needs to become easier to install for people who want to use it but have little knowledge in what's being asked of them to install

**Comment by ridhwaans** [comment]
@Dhop84 which parts do you want to change?
will look into more audio formats

**Comment by Dhop84** [comment]
It's more based on the install process of homehost as apposed to anything regarding audio formats, I kind of just jumped in to trwnh comment, which I shouldn't have, so I'm happy to delete my previous comment.

**Comment by ridhwaans** [comment]
@trwnh flac should work
